### ISSUE TITLE
Passing encoding type as json_ietf_val in pygNMI

### ISSUE THREAD

**Issue by apathak1990** [akarneliuk/pygnmi#1] opened 2021-01-05 08:34 UTC
Hi, 
I am trying to use pygnmi on Cisco IOS-XR device which works on  json_ietf_val 
The gNMI client is giving below error marked in BOLD below 
How can we pass encoding as json_ietf_val

Pls suggest the possible paramter

>>> from pygnmi.client import gNMIclient
>>> host = ('10.127.60.177', '57400')
>>> with gNMIclient(target=host, username='test2', password='cisco123', insecure=True) as gc:
...     result = gc.get(path=['openconfig-interfaces:interfaces'])
... 
Host: 10.127.60.177:57400
**Error: gNMI: unsupported get-request encoding: JSON**

**Comment by akarneliuk** [comment] 2021-01-05 18:18
Hey @apathak1990 ,

could you please past here the result of the `capabilities` request?

Thanks,
Anton

**Comment by akarneliuk** [comment] 2021-01-05 21:09
@apathak1990 , thanks for that.

Basically, the issue is that it (was) supposed that all the vendors have `json` encoding supported, what is not the case for your case. What you can do is:
```
gc.capabilities()
result = gc.get(path=['openconfig-interfaces:interfaces'])
```

When you collect capabilities, they are stored internally in the `gc` object and during `get` operation the pygnmi figure out automatically, what is supported: `json` or `json_ietf`.

Anyway, that was a valuable insight and thanks for raising PR. I've just created new release `0.3.6`, which adds the argument `encoding` to `get` method (check the example for get, it is updated as well), so that you can manually set the encoding bypassing the capabilities call.

Let me know if that works.

Thanks,
Anton

**Comment by apathak1990** [comment] 2021-01-06 15:37
Thanks Anton,
fixed worked !

>>> from pygnmi.client import gNMIclient
>>> host = ('10.127.60.177', '57400')
>>> with gNMIclient(target=host, username='test2', password='cisco123', insecure=True) as gc:
...     result = gc.get(path=['openconfig-interfaces:interfaces'], encoding='json_ietf')
... 
>>> result
{'notification': [{'timestamp': 1609947380475358261, 'update': [{'path': 'interfaces', 'val': {'interface': [{'name': 'Optics0/0/0/0', 'config': {'name': 'Optics0/0/0/0', 'type': 'iana-if-type:opticalChannel', 'description': 'L0'}, 'state': {'name': 'Optics0/0/0/0', 'enabled': True}}, {'name': 'Optics0/0/0/1', 'config': {'name': 'Optics0/0/0/1', 'type': 'iana-if-type:opticalChannel', 'description': 'L0'}, 'state': {'name': 'Optics0/0/0/1', 'enabled': True}}, {'name': 'Optics0/1/0/0', 'config': {'name': 'Optics0/1/0/0', 'type': 'iana-if-type:opticalChannel', 'enabled': False}, 'state': {'name': 'Optics0/1/0/0', 'enabled': False}}, {'name': 'Optics0/1/0/1', 'config': {'name': 'Optics0/1/0/1', 'type': 'iana-if-type:opticalChannel

**Comment by apathak1990** [comment] 2021-01-06 18:40
Hi @akarneliuk,

 could you pls add the encoding as a parameter for  set operation as well ? Let me know if you need it as a new Issue ?

I am seeing its hardcoded as json_val for update and replace operations . For Cisco IOS XR devices we would need json_ietf_val as TypedValue so better to have it parameterized 
https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#23-structured-data-types

```
replace_msg.append(Update(path=u_path, val=TypedValue(json_val=u_val)))
update_msg.append(Update(path=u_path, val=TypedValue(json_val=u_val)))
```

I did test by changing json_val to json_ietf_val and It worked on my Cisco IOS XR device 

```
replace_msg.append(Update(path=u_path, val=TypedValue(json_ietf_val=u_val)))
update_msg.append(Update(path=u_path, val=TypedValue(json_ietf_val=u_val)))
```

```
python set_tls.py
update {
  path {
    origin: "openconfig-system"
    elem {
      name: "system"
    }
  }
  val {
    json_ietf_val: "{\"config\": {\"hostname\": \"BH1_P2A4\"}}"
  }
}

response {
  path {
    origin: "openconfig-system"
    elem {
      name: "system"
    }
  }
  message {
  }
  op: UPDATE
}
message {
}
timestamp: 1609956691687050599

{'response': [{'path': 'system', 'op': 'UPDATE'}]}


```

**Comment by akarneliuk** [comment] 2021-01-06 23:21
Hey @apathak1990 ,

Thanks for further details. We'll fix that tomorrow and update you here.

Stay safe,
Anton

**Comment by akarneliuk** [comment] 2021-01-07 10:00
Hey @apathak1990 ,

We've issued new release `0.3.7`, where you have possibility to provide extra argument `encoding` to the `set` method. The default value is `json`, but you can change it to any supported (e.g., `json_ietf`). So the example would look like as:
```
result = gc.set(update=your_message, encoding='json_ietf')
```

Let us know if that works for you.

Best,
Anton

**Comment by akarneliuk** [comment] 2021-01-09 13:45
Hello,

If there further assistance is needed, feel free to raise the new issue. We'll close this one.

Best,
Anton

**Closed by akarneliuk** 2021-01-09 13:45 UTC
Labels: bug

**Comment by apathak1990** [comment] 2021-01-11 11:29
Thanks @akarneliuk  validated the changes on pygnmi 0.3.8 and works fine !

Thanks,
Avinash
